### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HDVinnie** [christofferok/laravel-emojione#1]
Upon installing this does this mean I can just type :s m i l i e: in my textarea on my app for comments and it will automatically show as 😄 when posted? Im new to laravel so please excuse my noobness.

```
<!-- Add comment -->
<div class="col-md-12">
  {!! Form::open(array('route' => array('comment_torrent', 'slug' => $torrent->slug, 'id' => $torrent->id))) !!}
  <div class="form-group">
    <label for="content">Your comment:</label>
    <textarea name="content" cols="30" rows="5" class="form-control"></textarea>
  </div>
  <button type="submit" class="btn btn-danger">{!! trans('traduction.save') !!}</button><label class="checkbox-inline"><input type="checkbox" name="confirmation"><strong>Anonymous Comment</strong></label>
  {!! Form::close() !!}
</div>
<!-- /Add comment -->
```

**Comment by christofferok** [comment]
When you are saving a comment, you might want to run the content through `LaravelEmojiOne::toShort($str)` to convert `😄` and other emoji to `:smile:` etc. 

```php
Comment::create([
  'content' => LaravelEmojiOne::toShort(request('content'))
]);
```
So if someone leaves a comment like `This is an awesome comment 😄🔥` it will be saved as `This is an awesome comment :smile: :fire:`

In your view where you display your comments you can use 
```php
@emojione($comment->content)
```
and that will convert `:smile:` and `😄` to the emojione equivalent. 

Does that make sense?

**Comment by HDVinnie** [comment]
Worked perfect thanks so much
