### ISSUE TITLE
LaravelEmojiOne::imageToShortname

### ISSUE THREAD

**Issue by winadv** [christofferok/laravel-emojione#10]
I would like to do the conversion below to insert the values into shortname in the database.
LaravelEmojiOne::imageToShortname($str);
But how to do that?
I'd like some help.
Thanks.

**Comment by tuimz** [comment]
Preferably you'd save the shortname or unicode equivalent in the database.

**Comment by christofferok** [comment]
The easiest is probably just to save the raw value in the database (if the DB can handle it) as @tuimz suggest. Then convert it to Emojione images when you need to display it.
```php
LaravelEmojiOne::toImage($str); // - native unicode + shortnames -> images (mixed input)
```

If your database can't handle unicode properly you might want to convert it to the shortnames before inserting it. That can be done using this: 
```php
LaravelEmojiOne::toShort($str); // - native unicode -> shortnames
```

And when you need to display that you use either one of these:
```php
LaravelEmojiOne::shortnameToImage($str); // - shortname -> images
LaravelEmojiOne::toImage($str); // - native unicode + shortnames -> images (mixed input)
```

Does that make sense?

**Comment by winadv** [comment]
@christofferok I would also like to know how to use laravel-emojione in editable div since this was the main need of what I was requesting above, since I did not want it to generate the editor automatically by emoji emoji as in github itself when a letter is inserted. I think you should have understood if you did not send a message. Hugs.
:smile:

**Comment by christofferok** [comment]
Hi @winadv. What you are looking for is probably a little outside the scope of this package. For usage on the frontend you might want to take a look at https://github.com/emojione/emojione/blob/master/examples/JAVASCRIPT.md
They also have more examples there for other use cases 👍
