### ISSUE TITLE
Add ascii as a config option

### ISSUE THREAD

**Issue by pincombe** [christofferok/laravel-emojione#12]
Hey, I was wondering if I could submit a pull request to bring the ascii config option across?

**Comment by christofferok** [comment]
Hey @pincombe. That sounds like a great idea 👍

**Comment by pincombe** [comment]
Thanks, I've added a pull request now :) 

#13

**Comment by christofferok** [comment]
Thanks! I have published a new release (4.0.1) with the PR included. 
https://github.com/christofferok/laravel-emojione/releases/tag/4.0.1
