### ISSUE TITLE
How Can i print all emojis for picking into Messages

### ISSUE THREAD

**Issue by vickymessii** [christofferok/laravel-emojione#14]
I want to add a button like facebook or other lots of sites are doing first they are printing all emojis and then they are using pick one by one in message or there comment.

**Comment by christofferok** [comment]
Hi @vickymessii. I think that would be better to do on the frontend with javascript. There might already be some emojipickers out there, but I'm not familiar with them. If you want to use EmojiOne with JS they have some examples here: https://github.com/emojione/emojione/blob/master/examples/JAVASCRIPT.md

Good luck ☺️
