### ISSUE TITLE
EmojiOne 3.1

### ISSUE THREAD

**Issue by HDVinnie** [christofferok/laravel-emojione#2]
Can you push a update so any of us using your great package can get the latest and greatest emojis?

**Comment by christofferok** [comment]
It looks like emojione has not updated their packages on https://packagist.org yet. When they are available I'll push out an update with the 3.1 dependencies 👍

**Comment by christofferok** [comment]
I've pushed a new version now, but if you are serving your own assets you should probably wait until they update the asset package on https://packagist.org/packages/emojione/assets

Already opened an issue with them, so they are aware of it ☺️ 
https://github.com/emojione/emojione/issues/522

**Comment by HDVinnie** [comment]
thanks
