### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by MrMooky** [christofferok/laravel-emojione#20]
Are you planing to support PHP 8 in the near future? Currently getting `christofferok/laravel-emojione[4.0.0, ..., 4.0.4] require php ~5.6|~7.0 -> your php version (8.0.5) does not satisfy that requirement.` when trying to update composer.

**Comment by christofferok** [comment]
If you could submit a PR I would be happy to merge it 👍🏼

**Comment by brusselsregular** [comment]
Also having this error - can't upgrade. 
Adding support for php 8 would be much appreciated!

**Comment by christofferok** [comment]
I merged the PR #21 and published a new version (v5.0.0). Hope this helps 👍🏼 

https://github.com/christofferok/laravel-emojione/releases/tag/5.0.0
