### ISSUE TITLE
Call to undefined function resolve()

### ISSUE THREAD

**Issue by nabidam** [christofferok/laravel-emojione#3]
Hi,
I'm on laravel 5.2,
when using `@emojione($text)` in blade, it shows an error with the title <i>Call to undefined function resolve()</i>
and I fixed it by changing line 24 in _LaravelEmojiOneServiceProvider.php_ file from:
`return "<?php echo resolve('".LaravelEmojiOne::class."')->toImage($expression); ?>";`
to
`return "<?php echo \LaravelEmojiOne::toImage($expression); ?>";`

**Comment by christofferok** [comment]
Seems like the `resolve` helper didn't come until laravel 5.3 so I've changed it to `App::make` and that seems to work in older laravel versions. 

Just pushed a new version 2.1.1 that you can try ☺️ 
https://github.com/christofferok/laravel-emojione/releases/tag/2.1.1 

You might have to run `php artisan view:clear` after updating to 2.1.1 so it's not using a cached version of your view files.
